import type { Metadata } from "next";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <div className="min-h-screen items-center justify-center font-sans bg-linear-to-br from-zinc-950 via-neutral-900 to-zinc-950">
          <Header showStats={true} isLoading={false} />
          <main className="container mx-auto">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
